apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-argo-application
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps/
    repoURL: https://github.com/joaosamouco/homelab
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true